/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author oscar
 */
public class ViewCompras extends javax.swing.JPanel {

    /**
     * Creates new form ViewCompras
     */
    public ViewCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_empresa = new javax.swing.JTextField();
        jtf_buscar_proveedor = new javax.swing.JTextField();
        jtf_nombre_proveedor = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_id_proveedor = new javax.swing.JTextField();
        jb_buscar_proveedor = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtb_proveedor = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtf_buscar_producto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jb_buscar_producto = new javax.swing.JButton();
        jb_buscar_proveedor1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtb_producto = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtb_proveedor2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jl_fecha = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(76, 175, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bolsa-de-dinero.png"))); // NOI18N
        jLabel8.setText("COMPRAS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 60));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(46, 125, 50));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(46, 125, 50));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 175, 80)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(46, 125, 50));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 125, 50));
        jLabel9.setText("Telefono");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel11.setBackground(new java.awt.Color(46, 125, 50));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 125, 50));
        jLabel11.setText("Buscar");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel12.setBackground(new java.awt.Color(46, 125, 50));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(46, 125, 50));
        jLabel12.setText("Empresa");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel13.setBackground(new java.awt.Color(46, 125, 50));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(46, 125, 50));
        jLabel13.setText("Nombre");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        jPanel3.add(jtf_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 210, 20));

        jtf_buscar_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscar_proveedorKeyReleased(evt);
            }
        });
        jPanel3.add(jtf_buscar_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 180, 20));
        jPanel3.add(jtf_nombre_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 210, 20));
        jPanel3.add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 210, 20));

        jLabel14.setBackground(new java.awt.Color(46, 125, 50));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(46, 125, 50));
        jLabel14.setText("ID ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel3.add(jtf_id_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, 20));

        jb_buscar_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jb_buscar_proveedor.setBorderPainted(false);
        jb_buscar_proveedor.setContentAreaFilled(false);
        jb_buscar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_proveedorActionPerformed(evt);
            }
        });
        jPanel3.add(jb_buscar_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jLabel23.setBackground(new java.awt.Color(46, 125, 50));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(46, 125, 50));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/camion-de-reparto.png"))); // NOI18N
        jLabel23.setText("Datos del Proveedor");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jtb_proveedor.setAutoCreateRowSorter(true);
        jtb_proveedor.setBackground(new java.awt.Color(254, 254, 254));
        jtb_proveedor.setBorder(null);
        jtb_proveedor.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jtb_proveedor.setForeground(new java.awt.Color(1, 1, 1));
        jtb_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Telefono", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_proveedor.setGridColor(new java.awt.Color(46, 125, 50));
        jtb_proveedor.setOpaque(false);
        jtb_proveedor.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jtb_proveedor.setSelectionForeground(new java.awt.Color(254, 254, 254));
        jScrollPane4.setViewportView(jtb_proveedor);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 430, 120));

        jButton4.setText("Seleccionar");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 790, 240));

        jPanel4.setBackground(new java.awt.Color(76, 175, 80));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 175, 80)));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(46, 125, 50));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(46, 125, 50));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paquete.png"))); // NOI18N
        jLabel15.setText("Producto");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jtf_buscar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_buscar_productoActionPerformed(evt);
            }
        });
        jPanel4.add(jtf_buscar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, 20));

        jLabel22.setBackground(new java.awt.Color(46, 125, 50));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(46, 125, 50));
        jLabel22.setText("Buscar");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jb_buscar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jb_buscar_producto.setBorderPainted(false);
        jb_buscar_producto.setContentAreaFilled(false);
        jb_buscar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_productoActionPerformed(evt);
            }
        });
        jPanel4.add(jb_buscar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        jb_buscar_proveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jb_buscar_proveedor1.setBorderPainted(false);
        jb_buscar_proveedor1.setContentAreaFilled(false);
        jb_buscar_proveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscar_proveedor1ActionPerformed(evt);
            }
        });
        jPanel4.add(jb_buscar_proveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jtb_producto.setAutoCreateRowSorter(true);
        jtb_producto.setBackground(new java.awt.Color(254, 254, 254));
        jtb_producto.setBorder(null);
        jtb_producto.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jtb_producto.setForeground(new java.awt.Color(1, 1, 1));
        jtb_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Precio de Compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_producto.setGridColor(new java.awt.Color(46, 125, 50));
        jtb_producto.setOpaque(false);
        jtb_producto.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jtb_producto.setSelectionForeground(new java.awt.Color(254, 254, 254));
        jScrollPane3.setViewportView(jtb_producto);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 130));

        jButton3.setText("Agregar");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));
        jPanel4.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 70, -1));

        jLabel21.setBackground(new java.awt.Color(46, 125, 50));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(46, 125, 50));
        jLabel21.setText("Cantidad");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 470, 240));

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 175, 80)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(46, 125, 50));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(46, 125, 50));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinero.png"))); // NOI18N
        jLabel24.setText("Compra");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jtb_proveedor2.setAutoCreateRowSorter(true);
        jtb_proveedor2.setBackground(new java.awt.Color(254, 254, 254));
        jtb_proveedor2.setBorder(null);
        jtb_proveedor2.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jtb_proveedor2.setForeground(new java.awt.Color(1, 1, 1));
        jtb_proveedor2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_proveedor2.setGridColor(new java.awt.Color(46, 125, 50));
        jtb_proveedor2.setOpaque(false);
        jtb_proveedor2.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jtb_proveedor2.setSelectionForeground(new java.awt.Color(254, 254, 254));
        jScrollPane5.setViewportView(jtb_proveedor2);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 760, 180));

        jButton5.setText("Registrar Compra");
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 270, 170, 30));

        jl_fecha.setBackground(new java.awt.Color(46, 125, 50));
        jl_fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jl_fecha.setForeground(new java.awt.Color(46, 125, 50));
        jl_fecha.setText("20-08-1997");
        jPanel5.add(jl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 120, -1));

        jLabel26.setBackground(new java.awt.Color(46, 125, 50));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(46, 125, 50));
        jLabel26.setText("0.0");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, 30));

        jLabel27.setBackground(new java.awt.Color(46, 125, 50));
        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(46, 125, 50));
        jLabel27.setText("TOTAL");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, 30));

        jLabel28.setBackground(new java.awt.Color(46, 125, 50));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(46, 125, 50));
        jLabel28.setText("Subtotal");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 30));

        jButton6.setText("Eliminar");
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 90, 30));

        jLabel29.setBackground(new java.awt.Color(46, 125, 50));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(46, 125, 50));
        jLabel29.setText("0.0");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 60, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1270, 320));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1310, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscar_productoActionPerformed

    private void jb_buscar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscar_proveedorActionPerformed

    private void jtf_buscar_proveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscar_proveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_buscar_proveedorKeyReleased

    private void jb_buscar_proveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscar_proveedor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscar_proveedor1ActionPerformed

    private void jtf_buscar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_buscar_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_buscar_productoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JButton jb_buscar_producto;
    public javax.swing.JButton jb_buscar_proveedor;
    public javax.swing.JButton jb_buscar_proveedor1;
    public javax.swing.JLabel jl_fecha;
    public javax.swing.JTable jtb_producto;
    public javax.swing.JTable jtb_proveedor;
    public javax.swing.JTable jtb_proveedor2;
    public javax.swing.JTextField jtf_buscar_producto;
    public javax.swing.JTextField jtf_buscar_proveedor;
    public javax.swing.JTextField jtf_empresa;
    public javax.swing.JTextField jtf_id_proveedor;
    public javax.swing.JTextField jtf_nombre_proveedor;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
