/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author oscar
 */
public class ViewReportes extends javax.swing.JPanel {

    /**
     * Creates new form ViewReportes
     */
    public ViewReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_buscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 175, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(46, 125, 50));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/redes.png"))); // NOI18N
        jButton2.setText("Reporte de Empleados");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 5));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(10);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 280, 90));

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jb_buscar.setContentAreaFilled(false);
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf1.png"))); // NOI18N
        jLabel8.setText("REPORTES");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 60));

        jButton3.setBackground(new java.awt.Color(46, 125, 50));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(254, 254, 254));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paquete.png"))); // NOI18N
        jButton3.setText("Reporte de Productos");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 5));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(10);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 280, 90));

        jButton4.setBackground(new java.awt.Color(46, 125, 50));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(254, 254, 254));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/red.png"))); // NOI18N
        jButton4.setText("Reporte de Clientes");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 5));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.setIconTextGap(10);
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 280, 90));

        jButton5.setBackground(new java.awt.Color(46, 125, 50));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(254, 254, 254));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/online-store.png"))); // NOI18N
        jButton5.setText("Reporte de Sucursales");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 5));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(10);
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 280, 90));

        jButton6.setBackground(new java.awt.Color(46, 125, 50));
        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(254, 254, 254));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/camion-de-reparto.png"))); // NOI18N
        jButton6.setText("Reporte de Proveedores");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 5));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6.setIconTextGap(10);
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 280, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_buscar;
    // End of variables declaration//GEN-END:variables
}
