/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author oscar
 */
public class ViewCompras extends javax.swing.JPanel {

    /**
     * Creates new form ViewCompras
     */
    public ViewCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_empresa = new javax.swing.JTextField();
        jtf_buscar = new javax.swing.JTextField();
        jtf_nombre_proveedor = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf_id_proveedor = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtb_proveedor = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jtf_subtotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_clientes = new javax.swing.JTable();
        jtf_total = new javax.swing.JTextField();
        jb_eliminar1 = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 175, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bolsa-de-dinero.png"))); // NOI18N
        jLabel8.setText("COMPRAS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 60));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(46, 125, 50));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 125, 50));
        jLabel9.setText("Telefono");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel11.setBackground(new java.awt.Color(46, 125, 50));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 125, 50));
        jLabel11.setText("Buscar");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel12.setBackground(new java.awt.Color(46, 125, 50));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(46, 125, 50));
        jLabel12.setText("Empresa");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel13.setBackground(new java.awt.Color(46, 125, 50));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(46, 125, 50));
        jLabel13.setText("Nombre");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel3.add(jtf_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 210, 20));

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyReleased(evt);
            }
        });
        jPanel3.add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 180, 20));
        jPanel3.add(jtf_nombre_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 210, 20));
        jPanel3.add(jtf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 20));

        jLabel14.setBackground(new java.awt.Color(46, 125, 50));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(46, 125, 50));
        jLabel14.setText("ID ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel3.add(jtf_id_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 210, 20));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jb_buscar.setBorderPainted(false);
        jb_buscar.setContentAreaFilled(false);
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });
        jPanel3.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jtb_proveedor.setAutoCreateRowSorter(true);
        jtb_proveedor.setBackground(new java.awt.Color(254, 254, 254));
        jtb_proveedor.setBorder(null);
        jtb_proveedor.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jtb_proveedor.setForeground(new java.awt.Color(1, 1, 1));
        jtb_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Empresa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_proveedor.setGridColor(new java.awt.Color(46, 125, 50));
        jtb_proveedor.setOpaque(false);
        jtb_proveedor.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jtb_proveedor.setSelectionForeground(new java.awt.Color(254, 254, 254));
        jScrollPane3.setViewportView(jtb_proveedor);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 430, 120));

        jLabel23.setBackground(new java.awt.Color(46, 125, 50));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(46, 125, 50));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/camion-de-reparto.png"))); // NOI18N
        jLabel23.setText("Datos del Proveedor");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 820, 190));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(46, 125, 50));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(46, 125, 50));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paquete.png"))); // NOI18N
        jLabel15.setText("Datos del Producto");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel17.setBackground(new java.awt.Color(46, 125, 50));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(46, 125, 50));
        jLabel17.setText("Descripcion");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 20));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 20));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, 20));

        jLabel19.setBackground(new java.awt.Color(46, 125, 50));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(46, 125, 50));
        jLabel19.setText("ID ");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel18.setBackground(new java.awt.Color(46, 125, 50));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(46, 125, 50));
        jLabel18.setText("Precio venta");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel16.setBackground(new java.awt.Color(46, 125, 50));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(46, 125, 50));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 220, 80));

        jLabel20.setBackground(new java.awt.Color(46, 125, 50));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(46, 125, 50));
        jLabel20.setText("Nombre");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel21.setBackground(new java.awt.Color(46, 125, 50));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(46, 125, 50));
        jLabel21.setText("Precio compra");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 20));

        jLabel22.setBackground(new java.awt.Color(46, 125, 50));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(46, 125, 50));
        jLabel22.setText("Buscar");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(46, 125, 50));
        jSeparator1.setForeground(new java.awt.Color(46, 125, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 440, 30));

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 130, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 420, 580));

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(46, 125, 50));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(46, 125, 50));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bolsa-de-dinero.png"))); // NOI18N
        jLabel10.setText("Datos de Compra");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel24.setBackground(new java.awt.Color(46, 125, 50));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(46, 125, 50));
        jLabel24.setText("Fecha");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 20));
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 110, 20));

        jLabel25.setBackground(new java.awt.Color(46, 125, 50));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(46, 125, 50));
        jLabel25.setText("Subtotal $");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 20));

        jLabel26.setBackground(new java.awt.Color(46, 125, 50));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(46, 125, 50));
        jLabel26.setText("TOTAL $");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jtf_subtotal.setBackground(new java.awt.Color(201, 201, 201));
        jtf_subtotal.setFont(new java.awt.Font("Tlwg Typo", 1, 17)); // NOI18N
        jtf_subtotal.setForeground(new java.awt.Color(208, 11, 9));
        jPanel4.add(jtf_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, -1));

        jtb_clientes.setAutoCreateRowSorter(true);
        jtb_clientes.setBackground(new java.awt.Color(254, 254, 254));
        jtb_clientes.setBorder(null);
        jtb_clientes.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jtb_clientes.setForeground(new java.awt.Color(1, 1, 1));
        jtb_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio de venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_clientes.setGridColor(new java.awt.Color(46, 125, 50));
        jtb_clientes.setOpaque(false);
        jtb_clientes.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jtb_clientes.setSelectionForeground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(jtb_clientes);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 540, 120));

        jtf_total.setBackground(new java.awt.Color(1, 1, 1));
        jtf_total.setFont(new java.awt.Font("Tlwg Typo", 1, 17)); // NOI18N
        jtf_total.setForeground(new java.awt.Color(27, 255, 0));
        jPanel4.add(jtf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 80, -1));

        jb_eliminar1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_eliminar1.setForeground(new java.awt.Color(46, 125, 50));
        jb_eliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del.png"))); // NOI18N
        jb_eliminar1.setText("Eliminar ");
        jb_eliminar1.setBorderPainted(false);
        jb_eliminar1.setContentAreaFilled(false);
        jPanel4.add(jb_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jb_guardar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(46, 125, 50));
        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disquette.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.setBorderPainted(false);
        jb_guardar.setContentAreaFilled(false);
        jPanel4.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 820, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtf_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_buscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JButton jb_buscar;
    public javax.swing.JButton jb_eliminar1;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JTable jtb_clientes;
    public javax.swing.JTable jtb_proveedor;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_empresa;
    public javax.swing.JTextField jtf_id_proveedor;
    public javax.swing.JTextField jtf_nombre_proveedor;
    public javax.swing.JTextField jtf_subtotal;
    public javax.swing.JTextField jtf_telefono;
    public javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
