/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author oscar
 */
public class ViewProductos extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductos
     */
    public ViewProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jtf_pventa = new javax.swing.JTextField();
        jb_reporte = new javax.swing.JButton();
        jtf_pcompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jb_actualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jb_guardar = new javax.swing.JButton();
        jtf_nombre = new javax.swing.JTextField();
        jb_cancelar = new javax.swing.JButton();
        jtf_id = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jb_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtf_descripcion = new javax.swing.JTextArea();
        jcb_categoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_productos = new javax.swing.JTable();

        setBackground(new java.awt.Color(76, 175, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paquete.png"))); // NOI18N
        jLabel8.setText("PRODUCTOS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        jb_buscar.setContentAreaFilled(false);
        jPanel1.add(jb_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));
        jPanel1.add(jtf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 229, 20));

        jLabel12.setFont(new java.awt.Font("AnjaliOldLipi", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Buscar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 70, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 60));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_nuevo.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(46, 125, 50));
        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-user.png"))); // NOI18N
        jb_nuevo.setText("Nuevo ");
        jb_nuevo.setBorderPainted(false);
        jb_nuevo.setContentAreaFilled(false);
        jPanel2.add(jb_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, -1, -1));

        jtf_pventa.setBackground(new java.awt.Color(254, 254, 254));
        jtf_pventa.setForeground(new java.awt.Color(46, 125, 50));
        jtf_pventa.setBorder(null);
        jPanel2.add(jtf_pventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 229, 20));

        jb_reporte.setBackground(new java.awt.Color(76, 175, 80));
        jb_reporte.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_reporte.setForeground(new java.awt.Color(46, 125, 50));
        jb_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf1.png"))); // NOI18N
        jb_reporte.setText("Reporte");
        jb_reporte.setBorderPainted(false);
        jb_reporte.setContentAreaFilled(false);
        jPanel2.add(jb_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, -1, -1));

        jtf_pcompra.setBackground(new java.awt.Color(254, 254, 254));
        jtf_pcompra.setForeground(new java.awt.Color(46, 125, 50));
        jtf_pcompra.setBorder(null);
        jPanel2.add(jtf_pcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 229, 20));

        jLabel3.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 125, 50));
        jLabel3.setText("Categoria");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, -1));

        jb_actualizar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_actualizar.setForeground(new java.awt.Color(46, 125, 50));
        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exchange.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        jb_actualizar.setBorderPainted(false);
        jb_actualizar.setContentAreaFilled(false);
        jPanel2.add(jb_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(46, 125, 50));
        jLabel4.setText("Descripcion");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 150, -1));

        jLabel2.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 125, 50));
        jLabel2.setText("Nombre ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 85, -1));

        jLabel10.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(46, 125, 50));
        jLabel10.setText("Precio Venta");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, -1));

        jb_guardar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(46, 125, 50));
        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disquette.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.setBorderPainted(false);
        jb_guardar.setContentAreaFilled(false);
        jPanel2.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jtf_nombre.setBackground(new java.awt.Color(254, 254, 254));
        jtf_nombre.setForeground(new java.awt.Color(46, 125, 50));
        jtf_nombre.setBorder(null);
        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 229, 20));

        jb_cancelar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(46, 125, 50));
        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x-button.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setBorderPainted(false);
        jb_cancelar.setContentAreaFilled(false);
        jPanel2.add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, -1, -1));

        jtf_id.setBackground(new java.awt.Color(254, 254, 254));
        jtf_id.setForeground(new java.awt.Color(46, 125, 50));
        jtf_id.setBorder(null);
        jtf_id.setCaretColor(new java.awt.Color(2, 119, 189));
        jtf_id.setOpaque(false);
        jPanel2.add(jtf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 229, 20));

        jSeparator3.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator3.setToolTipText("");
        jSeparator3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 230, 20));

        jSeparator4.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator4.setToolTipText("");
        jSeparator4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 230, 20));

        jSeparator5.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator5.setToolTipText("");
        jSeparator5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 230, 20));

        jb_eliminar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_eliminar.setForeground(new java.awt.Color(46, 125, 50));
        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del.png"))); // NOI18N
        jb_eliminar.setText("Eliminar");
        jb_eliminar.setBorderPainted(false);
        jb_eliminar.setContentAreaFilled(false);
        jPanel2.add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, -1, -1));

        jtf_descripcion.setColumns(20);
        jtf_descripcion.setRows(5);
        jScrollPane2.setViewportView(jtf_descripcion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 230, -1));

        jcb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Herramienta", "Maquinaria" }));
        jPanel2.add(jcb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 20));

        jLabel5.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 125, 50));
        jLabel5.setText("Precio Compra");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1230, 270));

        jtb_productos.setAutoCreateRowSorter(true);
        jtb_productos.setBackground(new java.awt.Color(254, 254, 254));
        jtb_productos.setBorder(null);
        jtb_productos.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jtb_productos.setForeground(new java.awt.Color(1, 1, 1));
        jtb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Precion de Compra", "Precio de Venta", "Descripcion", "Categoria "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_productos.setGridColor(new java.awt.Color(46, 125, 50));
        jtb_productos.setOpaque(false);
        jtb_productos.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jtb_productos.setSelectionForeground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(jtb_productos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 1230, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JButton jb_actualizar;
    public javax.swing.JButton jb_buscar;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_reporte;
    public javax.swing.JComboBox<String> jcb_categoria;
    public javax.swing.JTable jtb_productos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextArea jtf_descripcion;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_pcompra;
    public javax.swing.JTextField jtf_pventa;
    // End of variables declaration//GEN-END:variables
}
